/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  CourseContentResponseDto,
  ErrorResponse
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type syncCourseContentResponse200 = {
  data: CourseContentResponseDto
  status: 200
}

export type syncCourseContentResponse401 = {
  data: ErrorResponse
  status: 401
}

export type syncCourseContentResponseSuccess = (syncCourseContentResponse200) & {
  headers: Headers;
};
export type syncCourseContentResponseError = (syncCourseContentResponse401) & {
  headers: Headers;
};

export type syncCourseContentResponse = (syncCourseContentResponseSuccess | syncCourseContentResponseError)

export const getSyncCourseContentUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/content/sync`
}

/**
 * Synchronizes the enrollments of the logged user courses information. This endpoint retrieves the latest enrollment data for the courses the user is enrolled in and updates the local database accordingly. It ensures that the user's course enrollments are up-to-date with the Moodle site.
 * @summary Synchronize course users has been enrolled information
 */
export const syncCourseContent = async (courseId: number, options?: RequestInit): Promise<syncCourseContentResponse> => {

  return orvalFetch<syncCourseContentResponse>(getSyncCourseContentUrl(courseId),
  {
    ...options,
    method: 'POST'


  }
);}


export type getCourseUsersContentInfoResponse200 = {
  data: CourseContentResponseDto
  status: 200
}

export type getCourseUsersContentInfoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCourseUsersContentInfoResponseSuccess = (getCourseUsersContentInfoResponse200) & {
  headers: Headers;
};
export type getCourseUsersContentInfoResponseError = (getCourseUsersContentInfoResponse401) & {
  headers: Headers;
};

export type getCourseUsersContentInfoResponse = (getCourseUsersContentInfoResponseSuccess | getCourseUsersContentInfoResponseError)

export const getGetCourseUsersContentInfoUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/content/info`
}

/**
 * Get course Users Content sections and modules
 * @summary Get course users has been enrolled information
 */
export const getCourseUsersContentInfo = async (courseId: number, options?: RequestInit): Promise<getCourseUsersContentInfoResponse> => {

  return orvalFetch<getCourseUsersContentInfoResponse>(getGetCourseUsersContentInfoUrl(courseId),
  {
    ...options,
    method: 'GET'


  }
);}


