/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthLoginRequestDto,
  AuthOfflineRequestDto,
  AuthResponseDto,
  AuthTokenRequestDto,
  ErrorResponse
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type authTokenResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authTokenResponse401 = {
  data: ErrorResponse
  status: 401
}

export type authTokenResponseSuccess = (authTokenResponse200) & {
  headers: Headers;
};
export type authTokenResponseError = (authTokenResponse401) & {
  headers: Headers;
};

export type authTokenResponse = (authTokenResponseSuccess | authTokenResponseError)

export const getAuthTokenUrl = () => {




  return `http:///localhost:9090/api/public/auth/token`
}

/**
 * Receives host, username, and password. A JWT token is returned to be used in subsequent Moodle API calls. This endpoint is essential for authenticating users and establishing a secure session with the Moodle instance. The token can be used in the Authorization header of future requests to access protected resources and perform actions on behalf of the authenticated user.
 * @summary Get Moodle token
 */
export const authToken = async (authTokenRequestDto: AuthTokenRequestDto, options?: RequestInit): Promise<authTokenResponse> => {

  return orvalFetch<authTokenResponse>(getAuthTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authTokenRequestDto)
  }
);}


export type authOfflineResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authOfflineResponse401 = {
  data: ErrorResponse
  status: 401
}

export type authOfflineResponseSuccess = (authOfflineResponse200) & {
  headers: Headers;
};
export type authOfflineResponseError = (authOfflineResponse401) & {
  headers: Headers;
};

export type authOfflineResponse = (authOfflineResponseSuccess | authOfflineResponseError)

export const getAuthOfflineUrl = () => {




  return `http:///localhost:9090/api/public/auth/offline`
}

/**
 * Receives host, username, and password. A JWT token is returned to be used in subsequent Moodle API calls. This endpoint is essential for authenticating users and establishing a secure session with the Moodle instance. The token can be used in the Authorization header of future requests to access protected resources and perform actions on behalf of the authenticated user.
 * @summary Get Moodle token
 */
export const authOffline = async (authOfflineRequestDto: AuthOfflineRequestDto, options?: RequestInit): Promise<authOfflineResponse> => {

  return orvalFetch<authOfflineResponse>(getAuthOfflineUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authOfflineRequestDto)
  }
);}


export type authLoginResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authLoginResponse401 = {
  data: ErrorResponse
  status: 401
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
export type authLoginResponseError = (authLoginResponse401) & {
  headers: Headers;
};

export type authLoginResponse = (authLoginResponseSuccess | authLoginResponseError)

export const getAuthLoginUrl = () => {




  return `http:///localhost:9090/api/public/auth/credentials`
}

/**
 * Receives host, username, and password. A JWT token is returned to be used in subsequent Moodle API calls. This endpoint is essential for authenticating users and establishing a secure session with the Moodle instance. The token can be used in the Authorization header of future requests to access protected resources and perform actions on behalf of the authenticated user.
 * @summary Get Moodle token
 */
export const authLogin = async (authLoginRequestDto: AuthLoginRequestDto, options?: RequestInit): Promise<authLoginResponse> => {

  return orvalFetch<authLoginResponse>(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authLoginRequestDto)
  }
);}


export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponse401 = {
  data: ErrorResponse
  status: 401
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
export type authLogoutResponseError = (authLogoutResponse401) & {
  headers: Headers;
};

export type authLogoutResponse = (authLogoutResponseSuccess | authLogoutResponseError)

export const getAuthLogoutUrl = () => {




  return `http:///localhost:9090/api/auth/logout`
}

/**
 * Logout session. The token must be included in the Authorization header as a Bearer token.
 * @summary Logout session
 */
export const authLogout = async ( options?: RequestInit): Promise<authLogoutResponse> => {

  return orvalFetch<authLogoutResponse>(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


