/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  CourseLogsInfoRequestDto,
  CourseLogsInfoResponseDto,
  CourseLogsMetricsRequestDto,
  CourseLogsMetricsResponseDto,
  CourseLogsResponseDto,
  ErrorResponse,
  ImportCourseLogsBody
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type syncCourseLogsResponse200 = {
  data: CourseLogsResponseDto
  status: 200
}

export type syncCourseLogsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type syncCourseLogsResponseSuccess = (syncCourseLogsResponse200) & {
  headers: Headers;
};
export type syncCourseLogsResponseError = (syncCourseLogsResponse401) & {
  headers: Headers;
};

export type syncCourseLogsResponse = (syncCourseLogsResponseSuccess | syncCourseLogsResponseError)

export const getSyncCourseLogsUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/logs/sync`
}

/**
 * @summary Sync Moodle logs CSV
 */
export const syncCourseLogs = async (courseId: number, options?: RequestInit): Promise<syncCourseLogsResponse> => {

  return orvalFetch<syncCourseLogsResponse>(getSyncCourseLogsUrl(courseId),
  {
    ...options,
    method: 'POST'


  }
);}


export type getCourseLogsMetricsResponse200 = {
  data: CourseLogsMetricsResponseDto
  status: 200
}

export type getCourseLogsMetricsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCourseLogsMetricsResponseSuccess = (getCourseLogsMetricsResponse200) & {
  headers: Headers;
};
export type getCourseLogsMetricsResponseError = (getCourseLogsMetricsResponse401) & {
  headers: Headers;
};

export type getCourseLogsMetricsResponse = (getCourseLogsMetricsResponseSuccess | getCourseLogsMetricsResponseError)

export const getGetCourseLogsMetricsUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/logs/metrics`
}

/**
 * Get course logs metrics
 * @summary Get course logs metrics
 */
export const getCourseLogsMetrics = async (courseId: number,
    courseLogsMetricsRequestDto: CourseLogsMetricsRequestDto, options?: RequestInit): Promise<getCourseLogsMetricsResponse> => {

  return orvalFetch<getCourseLogsMetricsResponse>(getGetCourseLogsMetricsUrl(courseId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(courseLogsMetricsRequestDto)
  }
);}


export type getCourseLogsResponse200 = {
  data: CourseLogsInfoResponseDto
  status: 200
}

export type getCourseLogsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCourseLogsResponseSuccess = (getCourseLogsResponse200) & {
  headers: Headers;
};
export type getCourseLogsResponseError = (getCourseLogsResponse401) & {
  headers: Headers;
};

export type getCourseLogsResponse = (getCourseLogsResponseSuccess | getCourseLogsResponseError)

export const getGetCourseLogsUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/logs/info`
}

/**
 * Retrieves logs for a specific course with optional filtering by date range and selectable log columns.
 * @summary Get course logs with filters
 */
export const getCourseLogs = async (courseId: number,
    courseLogsInfoRequestDto: CourseLogsInfoRequestDto, options?: RequestInit): Promise<getCourseLogsResponse> => {

  return orvalFetch<getCourseLogsResponse>(getGetCourseLogsUrl(courseId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(courseLogsInfoRequestDto)
  }
);}


export type importCourseLogsResponse200 = {
  data: CourseLogsResponseDto
  status: 200
}

export type importCourseLogsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type importCourseLogsResponseSuccess = (importCourseLogsResponse200) & {
  headers: Headers;
};
export type importCourseLogsResponseError = (importCourseLogsResponse401) & {
  headers: Headers;
};

export type importCourseLogsResponse = (importCourseLogsResponseSuccess | importCourseLogsResponseError)

export const getImportCourseLogsUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/logs/import`
}

/**
 * @summary Import Moodle logs CSV
 */
export const importCourseLogs = async (courseId: number,
    importCourseLogsBody?: ImportCourseLogsBody, options?: RequestInit): Promise<importCourseLogsResponse> => {
    const formData = new FormData();
if(importCourseLogsBody?.logFile !== undefined) {
 formData.append(`logFile`, importCourseLogsBody.logFile);
 }

  return orvalFetch<importCourseLogsResponse>(getImportCourseLogsUrl(courseId),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}


