/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface AuthResponseDto {
  /** Access token for authentication */
  accessToken: string;
  /** Type of the token, usually "Bearer" */
  tokenType: string;
}
