/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface AuthTokenRequestDto {
  /** Moodle site URL */
  host: string;
  /** Moodle username */
  username: string;
  /** Moodle token */
  token: string;
  /** Database password encrypted with AES-256. This is used to securely store the database password in the system, ensuring that sensitive information is protected while allowing the application to access the database when needed. */
  dbPassword: string;
}
