/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional time aggregation interval for grouping logs by time buckets. If not provided, no time-based grouping is applied.
 */
export type CourseLogsMetricsRequestDtoInterval = typeof CourseLogsMetricsRequestDtoInterval[keyof typeof CourseLogsMetricsRequestDtoInterval];


export const CourseLogsMetricsRequestDtoInterval = {
  HOURLY: 'HOURLY',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  DAY_OF_WEEK: 'DAY_OF_WEEK',
} as const;
