/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { CourseLogsMetricsRequestDtoFieldsItem } from './courseLogsMetricsRequestDtoFieldsItem';
import type { CourseLogsMetricsRequestDtoFillGapsStrategy } from './courseLogsMetricsRequestDtoFillGapsStrategy';
import type { CourseLogsMetricsRequestDtoGroupByItem } from './courseLogsMetricsRequestDtoGroupByItem';
import type { CourseLogsMetricsRequestDtoInterval } from './courseLogsMetricsRequestDtoInterval';
import type { CourseLogsMetricsRequestFiltersDto } from './courseLogsMetricsRequestFiltersDto';
import type { CourseLogsMetricsRequestSortByItemDto } from './courseLogsMetricsRequestSortByItemDto';
import type { CourseLogsMetricsRequestTimeRangeDto } from './courseLogsMetricsRequestTimeRangeDto';

export interface CourseLogsMetricsRequestDto {
  /** Columns to include in response */
  fields?: CourseLogsMetricsRequestDtoFieldsItem[];
  timeRange?: CourseLogsMetricsRequestTimeRangeDto;
  groupBy?: CourseLogsMetricsRequestDtoGroupByItem[];
  /** Optional time aggregation interval for grouping logs by time buckets. If not provided, no time-based grouping is applied.  */
  interval?: CourseLogsMetricsRequestDtoInterval;
  fillGapsStrategy?: CourseLogsMetricsRequestDtoFillGapsStrategy;
  sortBy?: CourseLogsMetricsRequestSortByItemDto[];
  filters?: CourseLogsMetricsRequestFiltersDto;
}
