/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { CourseLogsInfoRequestSortItemDtoDirection } from './courseLogsInfoRequestSortItemDtoDirection';

export interface CourseLogsInfoRequestSortItemDto {
  field?: string;
  direction?: CourseLogsInfoRequestSortItemDtoDirection;
}
