/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export type CourseLogsMetricsRequestDtoFillGapsStrategy = typeof CourseLogsMetricsRequestDtoFillGapsStrategy[keyof typeof CourseLogsMetricsRequestDtoFillGapsStrategy];


export const CourseLogsMetricsRequestDtoFillGapsStrategy = {
  NONE: 'NONE',
  ZERO: 'ZERO',
} as const;
