/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { LogEntryDto } from './logEntryDto';
import type { PaginationInfoDto } from './paginationInfoDto';

export interface CourseLogsInfoResponseDto {
  page: PaginationInfoDto;
  /** List of log rows (dynamic fields based on columns) */
  content: LogEntryDto[];
}
