/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface CourseInformationDto {
  /** The unique identifier of the course. */
  id: number;
  /** The name of the course. */
  fullName: string;
  /** Indicates whether the user can view grades for the course. */
  showGrades: boolean;
  /** Indicates whether course completion tracking is enabled for the user. */
  enableCompletion: boolean;
  /** The date and time when the user's enrollment in the course starts. */
  startDate: string;
  /** The date and time when the user's enrollment in the course ends. */
  endDate: string;
  /** The date and time when the enrollment information was last modified. */
  timeModified: string;
}
