/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { CourseLogsInfoRequestDtoFieldsItem } from './courseLogsInfoRequestDtoFieldsItem';
import type { CourseLogsInfoRequestFiltersDto } from './courseLogsInfoRequestFiltersDto';
import type { CourseLogsInfoRequestPaginationDto } from './courseLogsInfoRequestPaginationDto';
import type { CourseLogsInfoRequestSortItemDto } from './courseLogsInfoRequestSortItemDto';
import type { CourseLogsInfoRequestTimeRangeDto } from './courseLogsInfoRequestTimeRangeDto';

export interface CourseLogsInfoRequestDto {
  timeRange?: CourseLogsInfoRequestTimeRangeDto;
  filters?: CourseLogsInfoRequestFiltersDto;
  /** Columns to include in response */
  fields?: CourseLogsInfoRequestDtoFieldsItem[];
  pagination?: CourseLogsInfoRequestPaginationDto;
  sort?: CourseLogsInfoRequestSortItemDto[];
  includeTotal?: boolean;
}
