/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export type CourseLogsMetricsRequestSortByItemDtoField = typeof CourseLogsMetricsRequestSortByItemDtoField[keyof typeof CourseLogsMetricsRequestSortByItemDtoField];


export const CourseLogsMetricsRequestSortByItemDtoField = {
  VALUE: 'VALUE',
  USER_ID: 'USER_ID',
  MODULE_ID: 'MODULE_ID',
  TIME: 'TIME',
  TIME_BUCKET: 'TIME_BUCKET',
} as const;
