/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { CourseLogsMetricsRequestSortByItemDtoDirection } from './courseLogsMetricsRequestSortByItemDtoDirection';
import type { CourseLogsMetricsRequestSortByItemDtoField } from './courseLogsMetricsRequestSortByItemDtoField';

export interface CourseLogsMetricsRequestSortByItemDto {
  field: CourseLogsMetricsRequestSortByItemDtoField;
  direction?: CourseLogsMetricsRequestSortByItemDtoDirection;
}
