/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface CourseContentModuleDto {
  /** Module ID */
  id: number;
  /** Module name */
  name: string;
  /** Module technical name */
  modName: string;
  /** Module URL */
  url: string;
  /** Module description */
  description: string;
  /** Is module visible */
  visible: boolean;
}
