/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export type CourseLogsMetricsRequestSortByItemDtoDirection = typeof CourseLogsMetricsRequestSortByItemDtoDirection[keyof typeof CourseLogsMetricsRequestSortByItemDtoDirection];


export const CourseLogsMetricsRequestSortByItemDtoDirection = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
