/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface CourseLogsMetricsRequestTimeRangeDto {
  /** @pattern ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$ */
  from?: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$ */
  to?: string;
}
