/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { CourseInformationDto } from './courseInformationDto';

export interface EnrollmentsResponseDto {
  /** List of courses the user is enrolled in, with updated enrollment information. */
  courses: CourseInformationDto[];
}
