/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

/**
 * Details about a specific field validation failure.
 */
export interface ErrorDetail {
  /** The name of the field that failed validation. */
  field: string;
  /** The specific validation error message for this field. */
  message: string;
}
