/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetail } from './errorDetail';

/**
 * Standard error response object for API failures.
 */
export interface ErrorResponse {
  /** A short, uppercase code identifying the error type (e.g., 'BAD_REQUEST'). */
  code: string;
  /** A human-readable explanation specific to this occurrence of the problem. */
  message: string;
  /** The date and time when the error occurred. */
  timestamp: string;
  /** A unique identifier for the request trace, useful for debugging. */
  traceId?: string;
  /** List of specific validation errors, if applicable. */
  errors?: ErrorDetail[];
}
