/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface LogEntryDto {
  /** Log entry ID */
  id: number;
  /**
     * Log creation time
     * @pattern ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$
     */
  timeCreated: string;
  /** ID of the course associated with the log */
  courseId: number;
  /** ID of the user associated with the log */
  userId: number;
  /** Full name of the user associated with the log */
  userFullName: string;
  /** ID of the module associated with the log */
  moduleId: number;
  /** Name of the module associated with the log */
  moduleName: string;
  /** Component associated with the log */
  component: string;
  /** ID of the component associated with the log */
  componentId: number;
  /** Name of the event associated with the log */
  eventName: string;
  /** ID of the event associated with the log */
  eventId: number;
  /** Name of the origin associated with the log */
  originName: string;
  /** ID of the origin associated with the log */
  originId: number;
  /** IP address associated with the log */
  ip: string;
}
