/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface PaginationInfoDto {
  /** Zero-based index of the current page */
  page: number;
  /** Number of items per page */
  size: number;
  /** Total number of elements matching the filters */
  totalElements: number;
  /** Total number of pages */
  totalPages: number;
  /** Whether this is the first page */
  first?: boolean;
  /** Whether this is the last page */
  last?: boolean;
  /** Whether the page has no content */
  empty?: boolean;
}
