/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of login method used by the Moodle site (e.g., APP, EMBEDDED, BROWSER).
 */
export type SiteInformationTypeOfLogin = typeof SiteInformationTypeOfLogin[keyof typeof SiteInformationTypeOfLogin];


export const SiteInformationTypeOfLogin = {
  APP: 'APP',
  EMBEDDED: 'EMBEDDED',
  BROWSER: 'BROWSER',
} as const;
