/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { SiteInformationTypeOfLogin } from './siteInformationTypeOfLogin';

/**
 * Basic information about the Moodle site.
 */
export interface SiteInformation {
  /** The name of the Moodle site. */
  siteName: string;
  /** The version of the Moodle site. */
  siteVersion: string;
  /** The URL of the Moodle site. */
  siteUrl: string;
  /** The type of login method used by the Moodle site (e.g., APP, EMBEDDED, BROWSER). */
  typeOfLogin: SiteInformationTypeOfLogin;
  /** The SSO login launch URL for the Moodle site, if applicable. */
  launchUrl?: string;
}
