/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type { SiteInformation } from './siteInformation';
import type { UserInformation } from './userInformation';

export interface SiteInfoResponseDto {
  site: SiteInformation;
  user: UserInformation;
}
