/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

export interface UserEnrollmentInfoCoursesInnerDto {
  /** The unique identifier of the course. */
  id: number;
  /** The full name of the course. */
  fullName: string;
}
