/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */

/**
 * Information about the authenticated user.
 */
export interface UserInformation {
  /** The unique identifier of the user. */
  id: number;
  /** The username of the user. */
  username: string;
  /** The full name of the user. */
  fullName: string;
  /** The first name of the user. */
  firstName: string;
  /** The last name of the user. */
  lastName: string;
}
