/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorResponse,
  SiteInfoResponseDto
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type syncSiteInfoResponse200 = {
  data: SiteInfoResponseDto
  status: 200
}

export type syncSiteInfoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type syncSiteInfoResponseSuccess = (syncSiteInfoResponse200) & {
  headers: Headers;
};
export type syncSiteInfoResponseError = (syncSiteInfoResponse401) & {
  headers: Headers;
};

export type syncSiteInfoResponse = (syncSiteInfoResponseSuccess | syncSiteInfoResponseError)

export const getSyncSiteInfoUrl = () => {




  return `http:///localhost:9090/api/sites/sync`
}

/**
 * Synchronize site information from the Moodle instance. This endpoint retrieves basic information about the Moodle site, such as the site name, version, and other relevant details. This information can be used to ensure that the integration is properly connected to the correct Moodle instance and to gather necessary metadata for further interactions with the Moodle API.
 * @summary Synchronize site information
 */
export const syncSiteInfo = async ( options?: RequestInit): Promise<syncSiteInfoResponse> => {

  return orvalFetch<syncSiteInfoResponse>(getSyncSiteInfoUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


export type getSiteInfoResponse200 = {
  data: SiteInfoResponseDto
  status: 200
}

export type getSiteInfoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getSiteInfoResponseSuccess = (getSiteInfoResponse200) & {
  headers: Headers;
};
export type getSiteInfoResponseError = (getSiteInfoResponse401) & {
  headers: Headers;
};

export type getSiteInfoResponse = (getSiteInfoResponseSuccess | getSiteInfoResponseError)

export const getGetSiteInfoUrl = () => {




  return `http:///localhost:9090/api/sites/info`
}

/**
 * Get site info and actual user logged
 * @summary Get site info and actual user logged
 */
export const getSiteInfo = async ( options?: RequestInit): Promise<getSiteInfoResponse> => {

  return orvalFetch<getSiteInfoResponse>(getGetSiteInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


