/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  CourseEnrollmentsResponseDto,
  ErrorResponse
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type syncCourseUsersEnrollmentsResponse200 = {
  data: CourseEnrollmentsResponseDto
  status: 200
}

export type syncCourseUsersEnrollmentsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type syncCourseUsersEnrollmentsResponseSuccess = (syncCourseUsersEnrollmentsResponse200) & {
  headers: Headers;
};
export type syncCourseUsersEnrollmentsResponseError = (syncCourseUsersEnrollmentsResponse401) & {
  headers: Headers;
};

export type syncCourseUsersEnrollmentsResponse = (syncCourseUsersEnrollmentsResponseSuccess | syncCourseUsersEnrollmentsResponseError)

export const getSyncCourseUsersEnrollmentsUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/enrollments/sync`
}

/**
 * Synchronizes the enrollments of the logged user courses information. This endpoint retrieves the latest enrollment data for the courses the user is enrolled in and updates the local database accordingly. It ensures that the user's course enrollments are up-to-date with the Moodle site.
 * @summary Synchronize course users has been enrolled information
 */
export const syncCourseUsersEnrollments = async (courseId: number, options?: RequestInit): Promise<syncCourseUsersEnrollmentsResponse> => {

  return orvalFetch<syncCourseUsersEnrollmentsResponse>(getSyncCourseUsersEnrollmentsUrl(courseId),
  {
    ...options,
    method: 'POST'


  }
);}


export type getCourseUsersEnrollmentsInfoResponse200 = {
  data: CourseEnrollmentsResponseDto
  status: 200
}

export type getCourseUsersEnrollmentsInfoResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCourseUsersEnrollmentsInfoResponseSuccess = (getCourseUsersEnrollmentsInfoResponse200) & {
  headers: Headers;
};
export type getCourseUsersEnrollmentsInfoResponseError = (getCourseUsersEnrollmentsInfoResponse401) & {
  headers: Headers;
};

export type getCourseUsersEnrollmentsInfoResponse = (getCourseUsersEnrollmentsInfoResponseSuccess | getCourseUsersEnrollmentsInfoResponseError)

export const getGetCourseUsersEnrollmentsInfoUrl = (courseId: number,) => {




  return `http:///localhost:9090/api/courses/${courseId}/enrollments/info`
}

/**
 * Retrieves the enrollment information for users enrolled in a specific course. This endpoint provides details about the users enrolled in the course, including their roles and enrollment status. It allows clients to access up-to-date enrollment information for a particular course on the Moodle site.
 * @summary Get course users has been enrolled information
 */
export const getCourseUsersEnrollmentsInfo = async (courseId: number, options?: RequestInit): Promise<getCourseUsersEnrollmentsInfoResponse> => {

  return orvalFetch<getCourseUsersEnrollmentsInfoResponse>(getGetCourseUsersEnrollmentsInfoUrl(courseId),
  {
    ...options,
    method: 'GET'


  }
);}


