/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetUserImagesProfileParams
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type getUserImagesProfileResponse200ImageJpeg = {
  data: Blob
  status: 200
}

export type getUserImagesProfileResponse200ImagePng = {
  data: Blob
  status: 200
}

export type getUserImagesProfileResponse200ImageGif = {
  data: Blob
  status: 200
}

export type getUserImagesProfileResponse200ImageWebp = {
  data: Blob
  status: 200
}

export type getUserImagesProfileResponse200ImageBmp = {
  data: Blob
  status: 200
}

export type getUserImagesProfileResponse200ImageTiff = {
  data: Blob
  status: 200
}

export type getUserImagesProfileResponse304ImageJpeg = {
  data: Blob
  status: 304
}

export type getUserImagesProfileResponse304ImagePng = {
  data: Blob
  status: 304
}

export type getUserImagesProfileResponse304ImageGif = {
  data: Blob
  status: 304
}

export type getUserImagesProfileResponse304ImageWebp = {
  data: Blob
  status: 304
}

export type getUserImagesProfileResponse304ImageBmp = {
  data: Blob
  status: 304
}

export type getUserImagesProfileResponse304ImageTiff = {
  data: Blob
  status: 304
}

export type getUserImagesProfileResponseSuccess = (getUserImagesProfileResponse200ImageJpeg | getUserImagesProfileResponse200ImagePng | getUserImagesProfileResponse200ImageGif | getUserImagesProfileResponse200ImageWebp | getUserImagesProfileResponse200ImageBmp | getUserImagesProfileResponse200ImageTiff) & {
  headers: Headers;
};
export type getUserImagesProfileResponseError = (getUserImagesProfileResponse304ImageJpeg | getUserImagesProfileResponse304ImagePng | getUserImagesProfileResponse304ImageGif | getUserImagesProfileResponse304ImageWebp | getUserImagesProfileResponse304ImageBmp | getUserImagesProfileResponse304ImageTiff) & {
  headers: Headers;
};

export type getUserImagesProfileResponse = (getUserImagesProfileResponseSuccess | getUserImagesProfileResponseError)

export const getGetUserImagesProfileUrl = (userId: number,
    params: GetUserImagesProfileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http:///localhost:9090/api/public/users/${userId}/images/profile?${stringifiedParams}` : `http:///localhost:9090/api/public/users/${userId}/images/profile`
}

/**
 * Get user profile image
 * @summary Get user profile image
 */
export const getUserImagesProfile = async (userId: number,
    params: GetUserImagesProfileParams, options?: RequestInit): Promise<getUserImagesProfileResponse> => {

  return orvalFetch<getUserImagesProfileResponse>(getGetUserImagesProfileUrl(userId,params),
  {
    ...options,
    method: 'GET'


  }
);}


