/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * UBUMonitor-Analytics
 * API documentation for UBUMonitor Analytics
 * OpenAPI spec version: 1.0.0
 */
import type {
  EnrollmentsResponseDto,
  ErrorResponse
} from '../../model';

import { orvalFetch } from '../../lib/orvalFetch';

export type syncUserEnrollmentsResponse200 = {
  data: EnrollmentsResponseDto
  status: 200
}

export type syncUserEnrollmentsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type syncUserEnrollmentsResponseSuccess = (syncUserEnrollmentsResponse200) & {
  headers: Headers;
};
export type syncUserEnrollmentsResponseError = (syncUserEnrollmentsResponse401) & {
  headers: Headers;
};

export type syncUserEnrollmentsResponse = (syncUserEnrollmentsResponseSuccess | syncUserEnrollmentsResponseError)

export const getSyncUserEnrollmentsUrl = () => {




  return `http:///localhost:9090/api/enrollments/sync`
}

/**
 * Synchronizes the enrollments of the logged user courses information. This endpoint retrieves the latest enrollment data for the courses the user is enrolled in and updates the local database accordingly. It ensures that the user's course enrollments are up-to-date with the Moodle site.
 * @summary Synchronize enrollments of the logged user courses information
 */
export const syncUserEnrollments = async ( options?: RequestInit): Promise<syncUserEnrollmentsResponse> => {

  return orvalFetch<syncUserEnrollmentsResponse>(getSyncUserEnrollmentsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


export type getActualUserEnrollmentsResponse200 = {
  data: EnrollmentsResponseDto
  status: 200
}

export type getActualUserEnrollmentsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getActualUserEnrollmentsResponseSuccess = (getActualUserEnrollmentsResponse200) & {
  headers: Headers;
};
export type getActualUserEnrollmentsResponseError = (getActualUserEnrollmentsResponse401) & {
  headers: Headers;
};

export type getActualUserEnrollmentsResponse = (getActualUserEnrollmentsResponseSuccess | getActualUserEnrollmentsResponseError)

export const getGetActualUserEnrollmentsUrl = () => {




  return `http:///localhost:9090/api/enrollments/info`
}

/**
 * Synchronizes or retrieves the enrollments of the logged user's courses information. This endpoint returns the latest enrollment data for the courses the user is enrolled in and updates the local database accordingly when applicable.
 * @summary Get user courses enrollments information
 */
export const getActualUserEnrollments = async ( options?: RequestInit): Promise<getActualUserEnrollmentsResponse> => {

  return orvalFetch<getActualUserEnrollmentsResponse>(getGetActualUserEnrollmentsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


